### ISSUE TITLE
Java Error while recording 

### ISSUE THREAD

**Issue by kimchi88** [introlab/odas_web#18]
Hi!
I am having an issue while trying to record separated tracks.

here a screenshot after receiving the error. 
I am using a Respeaker Mic array v2.0 with the default configuration "odas.cfg" found inside the respeaker github repository of usb_4_mic_array.

![javaissue](https://user-images.githubusercontent.com/40784190/44247137-cdee8d80-a1d1-11e8-8422-16ba332ab3c7.jpg)

Immediately after enabling the recording by checking the "determine if separated audio is recorded", I get the error in the screenshot. I've tried to run both as user and admin but no changes.

**Comment by GodCed** [comment]
Are you using the latest version pulled from master? This bug was fixed in (this issue)[https://github.com/introlab/odas_web/pull/8].

**Comment by kimchi88** [comment]
Hi and thanks for the solution.
I was using the version in the "download" section. After reinstalling ODAS using the latest version that bug is fixed and I can run the application succesfully.
However I still have a problem. Seems like when I test Odas with three people speaking around the Respeaker, the recordings files are created but are empty.
Any Hint?
I using the respeaker mic array 2.0 with the default configuration found in Respeaker Git repository.

here in attached a screenshot of what I see.

Thanks! 

![screenshot](https://user-images.githubusercontent.com/40784190/44387394-eda8ed00-a514-11e8-839c-391fc34c8f8f.png)

**Comment by GodCed** [comment]
It looks like there is no audio being streamed from ODAS to ODAS web. If you record from the respeaker in arecord using the same parameters as in your config file is the recorded audio correct?

Also, does the interfaces specified in your config file match does specified in ODAS Studio read me? You can post your config file here if you’re not sure.

**Comment by kimchi88** [comment]
Thanks to your README file I was able to record some wav file whie testing the source separation.
Still the output is not what I was expecting so I think there is still some work to do on the config file.

I attach it here together with a few records which I made while two video were streamed from the opposites sides of my respeaker and I was talking too


[audiosample.zip](https://github.com/introlab/odas_web/files/2308719/audiosample.zip)
[odasmy.zip](https://github.com/introlab/odas_web/files/2308722/odasmy.zip)




.

**Comment by GodCed** [comment]
Glad to hear that you can now record. The results you're getting are indeed quite... strange?
However, I would check that with the folks on the ODAS repo, as the sound processing itself is out of my scope. I saw a lot of people using the Respeaker array in the issues so you should be able to get support.

Thanks for your interest in our project!
